### ISSUE TITLE
Update for CWP 2.0

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp-recipe-basic-dev#1]
Suggested changes:

* Increase PHPUnit version to ^5.7
* Include `squizlabs/php_codesniffer` at ^3.0
* Remove `symfony/yaml` and phockito
* Add `lekoala/silverstripe-debugbar` once it is compatible with the recipe (see https://github.com/lekoala/silverstripe-debugbar/issues/93)

**Comment by robbieaverill** [comment]
Any issues here @tractorcow?

**Comment by tractorcow** [comment]
I would be careful with the dev recipe, as many projects end up including this in their deployed site. I'm not 100% sure about debugbar here.

As a quick check, see how many live CWP sites have both phpunit / phockito installed live and use that as an example. ;)

**Comment by tractorcow** [comment]
@robbieaverill maybe check that DebugBar has an `OnlyIf` check that only enables it if it's on dev mode, and is inert in live / test.

**Comment by NightJar** [comment]
So DebugBar will still ruin a good install, and the other two development requirements (phpunit & phpcs) are already included on `cwp-installer`, so this is just going to be closed, as it's no longer a necessary thing.

As per discussions elsewhere: Having a development recipe such as https://github.com/silverstripe/cwp-recipe-basic-dev/blob/master/composer.json involves pulling in requirements as normal requirements (not `require-dev`), meaning a bunch of development only intended tools get included in a production targeted build. This is not ideal as these may have performance penalties, or complicated setup to ensure that something that exists isn't used in production (such as @tractorcow's comment above). The decision was made to appropriately use the `require-dev` section of [`cwp-installer`](https://github.com/silverstripe/cwp-installer/blob/master/composer.json#L28) and [other recipes](https://github.com/silverstripe/cwp-core/blob/master/composer.json#L19), [as so](https://github.com/silverstripe/cwp/blob/master/composer.json#L18).
